inputs:
  version:
    description: 'Version'
    required: true
  build-number:
    description: 'Build number'
    required: true
  webhook-url:
    description: 'Slack webhook URL'
    required: true

runs:
  using: composite
  steps:
    - id: commit-info
      uses: ./.github/actions/commit-info
    - name: Send notification
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
        COMMIT_LINK: ${{ steps.commit-info.outputs.commit-link }}
        COMMIT_MESSAGE: ${{ steps.commit-info.outputs.commit-message }}
      with:
        payload: |
          {
             "blocks": [
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
                   "text": "@channel This is a plain text section block."
                 }
               },
               {
                 "type": "divider"
               },
               {
                 "type": "section",
                 "fields": [
                   {
                     "type": "mrkdwn",
                     "text": "*repository*\n<https://github.com/upsidr/app|upsidr/app>"
                   },
                   {
                     "type": "mrkdwn",
                     "text": "*ref*\n${{ github.ref }}"
                   }
                 ]
               },
               {
                 "type": "section",
                 "fields": [
                   {
                     "type": "mrkdwn",
                     "text": "*commit*\n<${{ env.COMMIT_LINK }}|${{ env.COMMIT_MESSAGE }}>"
                   },
                   {
                     "type": "mrkdwn",
                     "text": "*author*\n${{ github.event.sender.login }}"
                   }
                 ]
               },
               {
                 "type": "section",
                 "fields": [
                   {
                     "type": "mrkdwn",
                     "text": "*version*\n${{ inputs.version }}"
                   },
                   {
                     "type": "mrkdwn",
                     "text": "*build number*\n${{ inputs.build-number }}"
                   }
                 ]
               }
             ]
           }
