inputs:
  version:
    description: 'Version'
    required: true
  build-number:
    description: 'Build number'
    required: true
  webhook-url:
    description: 'Slack webhook URL'
    required: true

runs:
  using: composite
  steps:
    - id: get-merge-commit-message
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      uses: actions/github-script@v6
      with:
        script: |
          console.log('sha', context.sha);
          const { data: commit } = await github.rest.repos.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha,
          });
          return commit.commit.message.split('\n')[0];
    - id: notify-build-vars-pull-request-merged
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
      shell: bash
      run: |
        echo notify-build-vars-pull-request-merged
        COMMIT_LINK=${{ github.event.pull_request.html_url }}
        COMMIT_MESSAGE=$${{ steps.get-merge-commit-message.outputs.result }}
        echo "commit-link=${COMMIT_LINK}" >> $GITHUB_OUTPUT
        echo "commit-message=${COMMIT_MESSAGE}" >> $GITHUB_OUTPUT

    - id: notify-build-vars-pull-request-not-merged
      if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
      shell: bash
      run: |
        echo notify-build-vars-pull-request-not-merged
        COMMIT_LINK=${{ github.event.pull_request.html_url }}
        COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
        SHA=${{ github.event.pull_request.head.sha }}
        COMMIT_HASH=${SHA:0:7}
        echo "commit-link=${COMMIT_LINK}" >> $GITHUB_OUTPUT
        echo "commit-message=${COMMIT_MESSAGE} (${COMMIT_HASH})" >> $GITHUB_OUTPUT

    - id: notify-build-vars-workflow-dispatch
      if: github.event_name == 'workflow_dispatch'
      shell: bash
      run: |
        echo notify-build-vars-workflow_dispatch
        COMMIT_LINK=${{ github.event.repository.html_url }}/commits/${{ github.sha }}
        COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
        SHA=${{ github.sha }}
        COMMIT_HASH=${SHA:0:7}
        echo "commit-link=${COMMIT_LINK}" >> $GITHUB_OUTPUT
        echo "commit-message=${COMMIT_MESSAGE} (${COMMIT_HASH})" >> $GITHUB_OUTPUT

    - name: Send notification
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
        COMMIT_LINK: ${{ steps.notify-build-vars-pull-request-merged.outputs.commit-link || steps.notify-build-vars-pull-request-not-merged.outputs.commit-link }}
        COMMIT_MESSAGE: ${{ steps.notify-build-vars-pull-request-merged.outputs.commit-message || steps.notify-build-vars-pull-request-not-merged.outputs.commit-message }}
      with:
        payload: |
          {
             "blocks": [
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
                   "text": "@channel This is a plain text section block."
                 }
               },
               {
                 "type": "divider"
               },
               {
                 "type": "section",
                 "fields": [
                   {
                     "type": "mrkdwn",
                     "text": "*repository*\n<https://github.com/upsidr/app|upsidr/app>"
                   },
                   {
                     "type": "mrkdwn",
                     "text": "*ref*\n${{ github.ref }}"
                   }
                 ]
               },
               {
                 "type": "section",
                 "fields": [
                   {
                     "type": "mrkdwn",
                     "text": "*commit*\n<${{ env.COMMIT_LINK }}|${{ env.COMMIT_MESSAGE }}>"
                   },
                   {
                     "type": "mrkdwn",
                     "text": "*author*\n${{ github.event.sender.login }}"
                   }
                 ]
               },
               {
                 "type": "section",
                 "fields": [
                   {
                     "type": "mrkdwn",
                     "text": "*version*\n${{ inputs.version }}"
                   },
                   {
                     "type": "mrkdwn",
                     "text": "*build number*\n${{ inputs.build-number }}"
                   }
                 ]
               }
             ]
           }
