name: on hello1
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  hello1-1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }}'
  hello1-2:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }} 2'
  hello1-3:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }} 3'
