name: on hello2
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  hello2-1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }}'
  hello2-2:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }} 2'
  hello2-3:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }} 3'
