name: on hello6
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  hello6-1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }}'
  hello6-2:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }} 2'
  hello6-3:
    runs-on: ubuntu-latest
    steps:
      - name: Dump output
        shell: bash
        run: |
          echo 'Hello ${{ inputs.name }} 3'
