name: on push

on:
  push:
    branches:
      - main

jobs:
  send-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub
        shell: bash
        run: |
          echo '${{ toJson(github) }}'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set output
        id: vars
        run: |
          BUILD_NUMBER=$((${{ github.run_number }}-0))
          echo "build-number=${BUILD_NUMBER}" >> $GITHUB_OUTPUT
          VERSION=$(grep -oP '(?<=version:)\s*[0-9.]*' pubspec.yaml)
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT
      - name: Notify build info
        uses: ./.github/actions/notify-build
        with:
          version: ${{ steps.vars.outputs.version}}
          build-number: ${{ steps.vars.outputs.build-number}}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_DEV_URL }}
