name: on tag

on:
  push:
    tags:
      - v**
  workflow_dispatch:
    inputs:
      env:
        description: 'Checkout branch'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: release
      - name: cat version file
        run: |
          cat VERSION
      - name: checkout
        uses: actions/checkout@v3
      - name: cat version file
        run: |
          cat VERSION
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
