name: on tag

on:
  push:
    tags:
      - v**
  workflow_dispatch:
    inputs:
      env:
        description: 'Checkout branch'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.env || github.ref_name }}
      - name: cat version file
        run: |
          cat VERSION
      - name: checkout
        uses: actions/checkout@v3
      - name: cat version file
        run: |
          cat VERSION
