name: on workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'
      start-date:
        default: 2023-05-01
      cycle-unit:
        default: month

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: turara/typescript-action@feature/pr-metrics
        id: action-test
        with:
          owner: turara
          repo: github_actions_playground
          start-date: ${{ inputs.start-date }}
          cycle-unit: ${{ inputs.cycle-unit }}
          gmt: GMT+0900
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump output
        shell: bash
        run: |
          echo '${{ steps.action-test.outputs.metrics }}'

  # send-slack:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub
  #       shell: bash
  #       run: |
  #         echo '${{ toJson(github) }}'
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.head_ref }}
  #     - name: Set output
  #       id: vars
  #       run: |
  #         BUILD_NUMBER=$((${{ github.run_number }}-0))
  #         echo "build-number=${BUILD_NUMBER}" >> $GITHUB_OUTPUT
  #         VERSION=$(grep -oP '(?<=version:\s)[0-9.]*' pubspec.yaml)
  #         echo "version=v${VERSION}" >> $GITHUB_OUTPUT
  #         echo "version=v${VERSION}"
  #     - name: Notify build info
  #       uses: ./.github/actions/notify-build
  #       with:
  #         version: ${{ steps.vars.outputs.version}}
  #         build-number: ${{ steps.vars.outputs.build-number}}
  #         webhook-url: ${{ secrets.SLACK_WEBHOOK_DEV_URL }}
