name: on push

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Workflow dispatch env"
        required: false
        default: "dev"
  push:
    branches:
      - on_push_test

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Export webhook url
        if: github.event.inputs.env == 'dev'
        run: |
          echo WEBHOOK_URL=${{ github.event.inputs.env }}
      - name: Export webhook url
        if: github.event.inputs.env != 'dev'
        run: |
          echo "Triggered on push"
